server:
  servlet:
    context-path: /api
  port: 8088
#  error:
#    include-message: always
#    include-binding-errors: always
#    include-stacktrace: on_trace_param
#    include-exception: false

spring:
  application:
    name: reg-web-service
  datasource:
    name: cccc
    url: jdbc:mariadb://localhost:3306/cccc
    username: root
    password: my-secret-pw
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      use-new-id-generator-mappings: true
      ddl-auto: none
    properties:
      hibernate:
        id:
          new_generator_mappings: false

# Logging
logging:
  level:
    org.springframework: ERROR
    com.cccmbiz: DEBUG
  pattern:
    console: "%d %p %c{1.} [%t] %m%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file:
    name: target/reg-web-service.log




#spring.profiles.active=@spring.profiles.active@
#spring.application.name=reg-web-service
#
#logging.level.org.springframework=DEBUG
#logging.level.com.cccmbiz=DEBUG
#logging.pattern.console=%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint} %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n

## Output to a temp_folder/file
#logging.file=c:/temp/api.log
## Logging pattern for file
#logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%

#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://localhost:3306/cccc2019?zeroDateTimeBehavior=convertToNull
#spring.datasource.username=root
#spring.datasource.password=mysql
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=none
#spring.datasource.url=jdbc:mysql://localhost:3306/cccc2019?zeroDateTimeBehavior=convertToNull
#spring.datasource.username=root
#spring.datasource.password=mysql
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver